# Generated by Django 2.0.6 on 2018-06-21 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image', models.ImageField(upload_to='blog-pic')),
            ],
            options={
                'verbose_name_plural': 'BlogPosts',
            },
        ),
        migrations.CreateModel(
            name='HAWCUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('area', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('TMU', 'TMU'), ('Training', 'Training'), ('Other', 'Other')], default='Other', max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('paid', models.DateField(default='2018-01-01')),
            ],
        ),
    ]
